<?php

namespace App\Services\Ai;

use App\Contracts\AiProvider;
use App\Enums\AiProviderDriver;

class StubAiProvider implements AiProvider
{
    /**
     * @param  list<array{role: string, content: string}>  $messages
     * @param  array{context?: string|null}  $options
     * @return array{content: string, provider: string, model: string|null}
     */
    public function complete(array $messages, array $options = []): array
    {
        $lastUser = '';
        foreach (array_reverse($messages) as $message) {
            if (($message['role'] ?? '') === 'user') {
                $lastUser = trim((string) ($message['content'] ?? ''));
                break;
            }
        }

        if ($lastUser === '') {
            $lastUser = '(empty prompt)';
        }

        $context = trim((string) ($options['context'] ?? ''));
        $contextBlock = $context !== ''
            ? "Workspace context was supplied (stub does not call an external model).\n\n"
            : '';

        $content = <<<TEXT
[CRA AI stub — local template, not a live model]

{$contextBlock}You asked:
{$lastUser}

This response is generated by the local stub provider for development and Must-slice demos.
Human review is required for all compliance decisions. The assistant must not close vulns, submit reports, or change product data.
TEXT;

        return [
            'content' => $content,
            'provider' => AiProviderDriver::Stub->value,
            'model' => 'stub-local-template',
        ];
    }
}
