<?php

namespace App\Services\Ai;

use App\Contracts\AiProvider;
use App\Enums\AiProviderDriver;

class StubAiProvider implements AiProvider
{
    /**
     * @param  list<array{role: string, content: string}>  $messages
     * @param  array{context?: string|null}  $options
     * @return array{content: string, provider: string, model: string|null}
     */
    public function complete(array $messages, array $options = []): array
    {
        $lastUser = '';
        foreach (array_reverse($messages) as $message) {
            if (($message['role'] ?? '') === 'user') {
                $lastUser = trim((string) ($message['content'] ?? ''));
                break;
            }
        }

        if ($lastUser === '') {
            $lastUser = '(empty prompt)';
        }

        if (($options['mode'] ?? null) === 'document_analyse') {
            $filename = (string) ($options['filename'] ?? 'document.txt');
            $payload = [
                'document_summary' => 'Stub analysis of uploaded document for CRA workspace review.',
                'document_kind_guess' => 'other',
                'requirement_mappings' => [
                    [
                        'requirement_code' => null,
                        'confidence' => 0.4,
                        'rationale' => 'Stub provider cannot map requirements; human review required.',
                        'excerpt' => mb_substr($lastUser, 0, 120),
                    ],
                ],
                'evidence_mappings' => [
                    [
                        'suggested_evidence_type' => 'document',
                        'title_suggestion' => pathinfo($filename, PATHINFO_FILENAME) ?: 'Uploaded document',
                        'confidence' => 0.5,
                        'rationale' => 'Consider attaching this file as product evidence after human review.',
                    ],
                ],
                'gaps' => [
                    [
                        'kind' => 'coverage_gap',
                        'severity' => 'info',
                        'description' => 'Stub analysis does not verify completeness against CRA requirements.',
                        'suggested_action' => 'Have a compliance reviewer validate mappings before applying them.',
                    ],
                ],
                'human_review_required' => true,
                'disclaimer' => 'Suggestions only; no automated compliance decisions.',
            ];

            return [
                'content' => json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT) ?: '{}',
                'provider' => AiProviderDriver::Stub->value,
                'model' => 'stub-local-template',
            ];
        }

        $context = trim((string) ($options['context'] ?? ''));
        $contextBlock = '';
        if ($context !== '') {
            $excerptLimit = max(80, (int) config('ai.context_excerpt_chars', 400));
            $excerpt = mb_strlen($context) <= $excerptLimit
                ? $context
                : rtrim(mb_substr($context, 0, $excerptLimit - 1)) . '…';

            $contextBlock = <<<CTX
Workspace context was supplied (stub does not call an external model).

Grounded workspace context (excerpt):
{$excerpt}

CTX;
        }

        $content = <<<TEXT
[CRA AI stub — local template, not a live model]

{$contextBlock}You asked:
{$lastUser}

This response is generated by the local stub provider for development and Must-slice demos.
Human review is required for all compliance decisions. The assistant must not close vulns, submit reports, or change product data.
TEXT;

        return [
            'content' => $content,
            'provider' => AiProviderDriver::Stub->value,
            'model' => 'stub-local-template',
        ];
    }
}
